version: "3.9"

services:
  redpanda:
    container_name: kafka
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --memory
      - 256M
      - --overprovisioned
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-gateway
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      # Make sure your Python code uses KAFKA_BOOTSTRAP_SERVERS env var
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: telegram-messages
    networks:
      - appnet

networks:
  appnet:
    driver: bridge