server:
  address: 0.0.0.0
  port: 8080
  tomcat:
    apr: false

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO
    com.chatbotcal: INFO

openai:
  api-url: https://api.openai.com/v1/chat/completions

telegram:
  api-url: https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s

google:
  redirect-uri: http://localhost:8080/auth/callback


