server:
  address: 0.0.0.0
  port: 8443
  tomcat:
    apr: false
  ssl:
    enabled: true
    key-store: file:chatbot-calendar-service/config/keystore.p12
    key-store-password: techbankRootPsw
    key-store-type: PKCS12
    key-alias: myapp

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO
    com.chatbotcal: INFO

openai:
  api-url: https://api.openai.com/v1/chat/completions

telegram:
  api-url: https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s

google:
  redirect-uri: https://localhost:8443/auth/callback


