spring:
  datasource:
    url: jdbc:mysql://mysql:3306/telegramUserDetails?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate   # לא יוצרים schema ב־prod, רק מאמתים
  kafka:
    consumer:
      bootstrap-servers: kafka:9092

openai:
  api-key: ${OPENAI_API_KEY}

telegram:
  bot-token: ${TELEGRAM_TOKEN}

app:
  domain: https://myapp.com

google:
  redirect-uri: https://myapp.com/auth/callback
