server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/telegramUserDetails?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: create
  kafka:
    topic:
      telegram-messages: ${KAFKA_TOPIC}
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: kafka:9092
      group-id: telegramConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

openai:
  api-url: ${OPENAI_API_URL}
  api-key: ${OPENAI_API_KEY}

telegram:
  api-url: ${TELEGRAM_API_URL}
  bot-token: ${TELEGRAM_TOKEN}

google:
  redirect-uri: http://${APP_DOMAIN}/auth/callback
