server:
  port: 5001

spring:
  main:
    banner-mode: off
  data:
    rest:
      base-path: /chatbot-calendar/api
  jpa:
    # postgresSQL setting
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
    # mySQL jpa setting
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    #    show-sql: true
    #    hibernate:
    #     ddl-auto: update // if its create it will recreate the db table everytime that we build the project or restart app
  datasource:
    # postgresSQL data source
    url: jdbc:mysql://localhost:3306/telegramUserDetails?createDatabaseIfNotExist=true
    username: root
    password: techbankRootPsw

  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      # Connect to Kafka running in Docker via published port
      bootstrap-servers: localhost:19092
      group-id: telegramConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

openai:
  api-key: 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
  api-url: https://api.openai.com/v1/chat/completions